### ISSUE TITLE
Variable to set the Credentials

### ISSUE THREAD

**Issue by JT1301** [gscales/Powershell-Scripts#1]
Hi there,

I try to insert this function into my script.

At the beginning of the script I ask for a Exchange-Admin Credential and I like to hand over this Credentials into this script so I do not have to enter the username und password again and again.

Can you tell me how I can do this?

Regards,
JT

**Comment by gscales** [comment]
If you have a look at my examples you can pass in Credentials parameter eg https://github.com/gscales/Powershell-Scripts/blob/master/DumpCalSettings.ps1 that means it won't prompt for the password

**Comment by JT1301** [comment]
Hi,

ok now I can run the script without a password prompt but only for changes in my Mailbox. (Option 2)

I don't know how to set a ExchangeAdmin as the user.

Can you please take a look?

`$form1_Load={
	#TODO: Initialize Form Controls here
	$Credentials = Get-PSCredential domain\exchangeadmin
	$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://exchange.fqdn/PowerShell/ -Authentication Kerberos -Credential $Credentials
	Import-PSSession $Session
		Create-Folder -MailboxName mailbox@domain.de -NewFolderName Service_1234 -FolderClass IPF.Contact -Credentials $Credentials`
}
With the last comand I tried to hand over the credentials. What do I need to change in the "Set Credentials" part?

Thank you!
Regards,
JT

**Comment by gscales** [comment]
$service.Credentials 

Is what sets the EWS credentials that are used

$creds = New-Object System.Net.NetworkCredential($Credentials.UserName.ToString(),$Credentials.GetNetworkCredential().password.ToString())  

just changes the PSCredential into network credential to use

One thing to point out is that this will only work if the Exchange Admin has been granted rights to the target mailboxes via Add-MailboxPermission.

**Comment by JT1301** [comment]
> One thing to point out is that this will only work if the Exchange Admin has been granted rights to the target mailboxes via Add-MailboxPermission.

There was my mistake. I wasn't clear about this beacause I think if I insert the credentials manually it works without this settings?

Thank you for your help!
