### ISSUE TITLE
Export-GCECalendarToCSV.ps1 is missing the parameter redirectURL

### ISSUE THREAD

**Issue by IngoGege** [gscales/Powershell-Scripts#16]
Hi @gscales ,
the function Export-GCECalendarToCSV.ps1 is missing the parameter redirectURL and will therefore fail if you are using an app with a different redirectURL than "https://login.microsoftonline.com/common/oauth2/nativeclient".
Ciao,
Ingo

**Comment by gscales** [comment]
Thanks Ingo I've fixed that bug, updated the authentication now to use MSAL and added support for the client credentials flow
