### ISSUE TITLE
unReadModule : add Inbox subfolders and In-Place Archive Inbox to the Results

### ISSUE THREAD

**Issue by GodfatherX64** [gscales/Powershell-Scripts#17]
when useing the script, it only read the inbox and not the subfolders inside inbox or the in-place archive inbox, is it possible to add them to the results of the unreadmodule.ps1

**Comment by gscales** [comment]
see https://github.com/gscales/Powershell-Scripts/blob/master/unReadModulesf.ps1 i've added a -AllItems switch will make the script use the AllItems Folder (equivlent to messages in the Graph API) and the -Archive switch which will make it use the archive

**Comment by GodfatherX64** [comment]
thanks for the support , it works and shows different results from the one before but it also gives this error before showing the results

VERBOSE: Using EWS dll from Local Directory
Exception calling "ResolveName" with "1" argument(s): "No mailbox with such guid."
At C:\scripts\unread.ps1:76 char:4
+             $Name = $service.ResolveName($MailboxName)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ServiceResponseException

VERBOSE: Exchange Version 15
VERBOSE: Update Version

*My On-premise Exchange Server is 2019 CU 12 + SU May
**The command i use
(Get-UnReadMessageCount -MailboxName user@company.com -url https://mail.company.com/EWS/Exchange.asmx -useImpersonation -AllItems -basicAuth -Verbose)

and i need to ask , are the result shown per mail **conversation** , like the total sum of the conversations and replies to the same mail thread, or it shows the sum of all emails every single thread and reply alone?
