### ISSUE TITLE
Error: "This document already has a 'DocumentElement' node."

### ISSUE THREAD

**Issue by DimaRazb** [gscales/Powershell-Scripts#7]
Works quite good for me, but it throw an error:

PS C:\> $rptCollection = @()
PS C:\> $Last24Junk = Get-MailDetailSpamReport -StartDate (Get-Date).AddDays(-1) -EndDate (Get-Date)
PS C:\> foreach($JunkMail in $Last24Junk){
>>    $RptObject = New-Object PsObject
>>    $JunkMail.psobject.properties | % {
>>       $RptObject | Add-Member -NotePropertyName $_.Name -NotePropertyValue $_.Value
>>    }
>>    $Details = $JunkMail | Get-MessageTraceDetail -StartDate (Get-Date).AddDays(-2) -EndDate (Get-Date) | Where-Object {$_.Event -eq "Spam"}
>>    $XMLDoc = [XML]$Details.Data
>>    $MEPNodes = $XMLDoc.GetElementsByTagName("MEP")
>>    for($nodeval=0;$nodeval -lt $MEPNodes.Count;$nodeval++){
>>       $Key = $MEPNodes[$nodeval].Attributes[0].Value.ToString()
>>    $Value = $MEPNodes[$nodeval].Attributes[1].Value.ToString()
>>    Add-Member -InputObject $RptObject -NotePropertyName ($Key) -NotePropertyValue ($Value)
>>
>>    }
>>    $rptCollection += $RptObject
>>
>> }
Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "This document already has a 'DocumentElement' node."
At line:7 char:4
+    $XMLDoc = [XML]$Details.Data
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument

Any ideas how to fix it?
Thanks for the nice solution btw.

**Comment by gscales** [comment]
I would suggest you echo out the of $Details.Data so you can see what is being returned or use something like

$Details.Data | out-file c:\temp\log.txt etc

most likely that value is either Null or potentially there is byte order mark as the first character if its the byte order mark just try

[XML]$Details.Data.Substring(1)

**Comment by DimaRazb** [comment]
Yep, nothing in the log file
$Details.Data | out-file c:\temp\log.txt etc
And seems the same emptiness in substring value.

PS C:\> [XML]$Details.Data.Substring(1)
You cannot call a method on a null-valued expression.
At line:1 char:1
+ [XML]$Details.Data.Substring(1)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by gscales** [comment]
So from that it appears the value is null so all you can do is implement a check to skip the property if it is null I've patched the code https://github.com/gscales/Powershell-Scripts/blob/master/detailSpamReport.ps1

**Comment by DimaRazb** [comment]
Great, thank you Glen!
