### ISSUE TITLE
Unable to export Contacts to VCF

### ISSUE THREAD

**Issue by vitusq** [gscales/Powershell-Scripts#9]
Hi 

I've downloaded the entire "PoweShell-scripts-master" folder.
I'm trying to export Contacts from a Specific users mailbox (ABC@xyz.com) to VCF but i get no Output. Maybe I'm executing the script wrong. 

1. I've opened PowerShell and connected it to Exchange Online
2. I've executed the script in the following way: 
.\EWSContactFunctions.ps1 Export-Contact -MailboxName "abc@xyz.com" -EmailAddress "abc@xyz.com" -FileName "c:\temp3\Temp.vcf"

but I get no ouput file. Maybe i'm doing it wrong. 
Can you please help/correct me to get it done right ?

**Comment by gscales** [comment]
ExportEXC-Contact will only export one contact (that of the contact with an EmailAddress that matches the EmailAddress paraemter) to a VCF file. I think you want to export all contacts to a single VCF ? have a look at the latest commit and the cmdlet Export-EXCContacts which should do all contacts to a single VCF eg Export-EXCContacts -MailboxName gscales@datarumble.com -FileName c:\temp\me1.vcf
